import { useState, useEffect, useMemo } from "react";

const G = () => `${Date.now()}-${Math.random().toString(36).slice(2,5)}`;

const PRODS = [{id:'prod-001',n:'মিনিকেট চাল (১ কেজি)',p:68,u:'কেজি',c:'চাল',img:'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&q=70',stock:100,hot:true},{id:'prod-002',n:'বাসমতি চাল (১ কেজি)',p:95,u:'কেজি',c:'চাল',img:'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=300&q=70',stock:60,hot:false},{id:'prod-003',n:'সয়াবিন তেল (२ লিটার)',p:380,u:'বোতল',c:'তেল',img:'https://images.unsplash.com/photo-1620706859477-e4abc8a7b2a7?w=300&q=70',stock:50,hot:true},{id:'prod-004',n:'সরিষার তেল (১ লিটার)',p:220,u:'বোতল',c:'তেল',img:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&q=70',stock:40,hot:false},{id:'prod-005',n:'দেশি আলু (১ কেজি)',p:55,u:'কেজি',c:'সবজি',img:'https://images.unsplash.com/photo-1518977676601-b53f02bad67b?w=300&q=70',stock:200,hot:true},{id:'prod-006',n:'টমেটো (১ কেজি)',p:80,u:'কেজি',c:'সবজি',img:'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=300&q=70',stock:80,hot:false},{id:'prod-007',n:'পেঁয়াজ (১ কেজি)',p:60,u:'কেজি',c:'সবজি',img:'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=300&q=70',stock:150,hot:false},{id:'prod-008',n:'সবরি কলা (১ ডজন)',p:120,u:'ডজন',c:'ফল',img:'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=300&q=70',stock:30,hot:true},{id:'prod-009',n:'আম – রাজশাহী (১ কেজি)',p:150,u:'কেজি',c:'ফল',img:'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=300&q=70',stock:6,hot:false},{id:'prod-010',n:'চানাচুর (१५০ গ্রাম)',p:45,u:'প্যাকেট',c:'নাস্তা',img:'https://images.unsplash.com/photo-1601050690597-df056fb46b45?w=300&q=70',stock:100,hot:false},{id:'prod-011',n:'কোকা-কোলা (৫০0 মিলি)',p:40,u:'বোতল',c:'পানীয়',img:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&q=70',stock:0,hot:false},{id:'prod-012',n:'ডেটল সাবান',p:55,u:'পিস',c:'গৃহস্থালি',img:'https://images.unsplash.com/photo-1584515933487-779824d29309?w=300&q=70',stock:60,hot:false},{id:'prod-013',n:'মসুর ডাল (১ কেজি)',p:140,u:'কেজি',c:'ডাল',img:'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300&q=70',stock:90,hot:false},{id:'prod-014',n:'হলুদ গুড়া (२०० গ্রাম)',p:45,u:'প্যাকেট',c:'ডাল',img:'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=300&q=70',stock:80,hot:false}];

const CATS = ['সব','চাল','তেল','সবজি','ফল','নাস্তা','পানীয়','গৃহস্থালি','ডাল'];

const formatDate = (iso) => { const d = new Date(iso); return d.toLocaleString('bn-BD', { dateStyle: 'medium', timeStyle: 'short' }); };

const isValidPhone = (phone) => /^01\d{9}$/.test(phone.replace(/[-\s]/g, ''));

export default function App() { const [view, setView] = useState('STORE'); const [prods, setProds] = useState(PRODS); const [cart, setCart] = useState([]); const [adminAuth, setAdminAuth] = useState(false); const [adminPw, setAdminPw] = useState(''); const [placing, setPlacing] = useState(false); const [chkForm, setChkForm] = useState({name:'',phone:'',addr:''}); const [toast, setToast] = useState(null); const showToast = (msg, type='ok') => { setToast({msg, type}); setTimeout(() => setToast(null), 2800); };

const addToCart = (prod) => { const prodData = prods.find(p => p.id === prod.id); if (!prodData || prodData.stock <= 0) { showToast('স্টকে পণ্য নেই!', 'w'); return; } setCart(prev => { const ex = prev.find(i => i.id === prod.id); const currentQty = ex ? ex.qty : 0; if (currentQty + 1 > prodData.stock) { showToast(`সর্বোচ্চ ${prodData.stock}টি কিনতে পারবেন!`, 'w'); return prev; } return ex ? prev.map(i => i.id===prod.id ? {...i, qty:i.qty+1} : i) : [...prev, {...prod, qty:1}]; }); showToast(`${prod.n} ব্যাগে যুক্ত!`); };

const logoutAdmin = () => { setAdminAuth(false); setAdminPw(''); };

const placeOrder = async (e) => { e.preventDefault(); if (!chkForm.name.trim()) { showToast('দয়া করে নাম দিন!', 'w'); return; } if (!isValidPhone(chkForm.phone)) { showToast('৳বৈধ মোবাইল নম্বর দিন! (01XXXXXXXXX)', 'w'); return; } if (!chkForm.addr.trim()) { showToast('দয়া করে ঠিকানা দিন!', 'w'); return; } setPlacing(true); await new Promise(r => setTimeout(r, 700)); setPlacing(false); showToast('অর্ডার সম্পন্ন!'); setView('STORE'); };

return (
<div style={{fontFamily:'Noto Sans Bengali, sans-serif', minHeight:'100vh', background:'#f5f7f5'}}>
{toast && <div style={{position:'fixed', bottom:20, left:'50%', transform:'translateX(-50%)', zIndex:9999, background:toast.type==='ok'?'#059669':'#d97706', color:'white', padding:'12px 24px', borderRadius:99, boxShadow:'0 4px 12px rgba(0,0,0,.15)'}}>{toast.msg}</div>}
<header style={{background:'white', padding:'16px 20px', boxShadow:'0 2px 8px rgba(0,0,0,.1)', marginBottom:'20px'}}>
<div style={{maxWidth:1200, margin:'0 auto', display:'flex', justifyContent:'space-between', alignItems:'center'}}>
<h1 style={{fontSize:'24px', fontWeight:'900', color:'#065f46'}}>🛒 সামসুল'স গ্রোসরি</h1>
<div style={{display:'flex', gap:'12px'}}>
<button onClick={()=>setView('STORE')} style={{padding:'10px 16px', borderRadius:'8px', border:'none', background:view==='STORE'?'#059669':'white', color:view==='STORE'?'white':'#065f46', cursor:'pointer', fontWeight:'700'}}>স্টোর</button>
<button onClick={()=>setView('ADMIN')} style={{padding:'10px 16px', borderRadius:'8px', border:'none', background:view==='ADMIN'?'#059669':'white', color:view==='ADMIN'?'white':'#065f46', cursor:'pointer', fontWeight:'700'}}>অ্যাডমিন</button>
<button onClick={()=>setView('CHECKOUT')} style={{padding:'10px 16px', borderRadius:'8px', border:'none', background:view==='CHECKOUT'?'#059669':'white', color:view==='CHECKOUT'?'white':'#065f46', cursor:'pointer', fontWeight:'700'}}>চেকআউট ({cart.length})</button>
</div>
</div>
</header>
<main style={{maxWidth:1200, margin:'0 auto', padding:'20px'}}>
{view==='STORE' && <div><h2>পণ্যসমূহ</h2><div style={{display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(200px, 1fr))', gap:'16px', marginTop:'16px'}}>{prods.map(p => <div key={p.id} style={{background:'white', padding:'16px', borderRadius:'12px', boxShadow:'0 2px 8px rgba(0,0,0,.1)', cursor:'pointer'}}><img src={p.img} alt={p.n} style={{width:'100%', height:'150px', objectFit:'cover', borderRadius:'8px', marginBottom:'12px'}} /><h3 style={{fontSize:'14px', fontWeight:'700', marginBottom:'8px'}}>{p.n}</h3><p style={{fontSize:'16px', fontWeight:'900', color:'#059669', marginBottom:'8px'}}>৳{p.p}</p><p style={{fontSize:'12px', color:'#6b7280', marginBottom:'12px'}}>স্টক: {p.stock}</p><button onClick={()=>addToCart(p)} disabled={p.stock===0} style={{width:'100%', padding:'10px', background:p.stock===0?'#ccc':'#059669', color:'white', border:'none', borderRadius:'8px', cursor:p.stock===0?'not-allowed':'pointer', fontWeight:'700'}}>যোগ করুন</button></div>)}</div></div>} {view==='CHECKOUT' && <div><h2>চেকআউট</h2><form onSubmit={placeOrder} style={{display:'flex', flexDirection:'column', gap:'12px', maxWidth:'400px'}}><input required type="text" value={chkForm.name} onChange={e=>setChkForm({...chkForm, name:e.target.value})} placeholder="নাম" style={{padding:'10px', borderRadius:'8px', border:'1px solid #e0e0e0'}} /><input required type="tel" value={chkForm.phone} onChange={e=>setChkForm({...chkForm, phone:e.target.value})} placeholder="মোবাইল নম্বর" style={{padding:'10px', borderRadius:'8px', border:'1px solid #e0e0e0'}} /><textarea required value={chkForm.addr} onChange={e=>setChkForm({...chkForm, addr:e.target.value})} placeholder="ঠিকানা" style={{padding:'10px', borderRadius:'8px', border:'1px solid #e0e0e0'}} /><button type="submit" disabled={placing} style={{padding:'12px', background:'#059669', color:'white', border:'none', borderRadius:'8px', fontWeight:'700', cursor:'pointer'}}>{placing?'প্রক্রিয়া করছে...':'অর্ডার করুন'}</button></form></div>} {view==='ADMIN' && !adminAuth && <div style={{maxWidth:'300px'}}><h2>অ্যাডমিন লগইন</h2><input type="password" value={adminPw} onChange={e=>setAdminPw(e.target.value)} placeholder="পাসওয়ার্ড" style={{width:'100%', padding:'10px', marginBottom:'12px', borderRadius:'8px', border:'1px solid #e0e0e0'}} /><button onClick={()=>adminPw==='admin2024'?setAdminAuth(true):showToast('ভুল পাসওয়ার্ড!','w')} style={{width:'100%', padding:'10px', background:'#059669', color:'white', border:'none', borderRadius:'8px', fontWeight:'700', cursor:'pointer'}}>লগইন</button></div>} {view==='ADMIN' && adminAuth && <div><h2>অ্যাডমিন প্যানেল</h2><button onClick={logoutAdmin} style={{padding:'10px 16px', background:'#dc2626', color:'white', border:'none', borderRadius:'8px', fontWeight:'700', cursor:'pointer', marginBottom:'16px'}}>লগআউট</button><h3>পণ্য সংখ্যা: {prods.length}</h3><h3>কার্টে আইটেম: {cart.length}</h3></div>} </main> </div> ); }